- name: Update apt 
  become_user: root
  become: true 
  shell:  apt update                                                                                                 
  args:
    executable: /bin/bash

- name: Install phyton3-pip 
  become_user: root
  become: true 
  command: sudo apt install python3-pip -y 

- name: Install pexpect
  become_user: root
  become: true 
  shell: pip3 install pexpect                                                                                                 
  args:
    executable: /bin/bash

- name: "Create Android SDK directory"
  file:
    path: /home/vagrant/android-sdk-linux/
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0777

- name: "Download and decompress Android-SDK from {{ linux_android_commandline_url }}"
  unarchive: 
    copy: no
    src: "{{ linux_android_commandline_url }}"
    dest:  /home/vagrant/android-sdk-linux
    force: yes
    owner: vagrant
    group: vagrant
    mode: 0777

- name: Create bashrc
  file: 
    path: /home/vagrant/.bashrc
    state: touch
    mode: "u=rw,g=r,o=r"

- name: "Add new path into user environment"
  lineinfile: 
    dest: /etc/environment
    regexp: ^PATH
    line: PATH="/home/vagrant/appium/node-v12.4.0-linux-x64/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/android-sdk-linux/tools:/home/vagrant/android-sdk-linux/tools/bin:/home/vagrant/android-sdk-linux/platform-tools"
    state: present
    mode: 0644
    owner: root
    group: root
    backup: yes

- name: "Add new path into etc profile"
  become_user: root
  lineinfile:
    dest: /etc/profile
    state: present
    backrefs: no
    line: "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64\nexport ANDROID_AVD_HOME=/home/vagrant/.android/avd:$ANDROID_AVD_HOME\nexport ANDROID_HOME=/home/vagrant/android-sdk-linux:$ANDROID_HOME\nexport PATH=$PATH:$ANDROID_HOME/tools\nexport PATH=$PATH:$ANDROID_HOME/tools/bin\nexport PATH=$PATH:$ANDROID_HOME/platform-tools"

- name: Touch the file .profile
  become_user: vagrant
  become: yes
  file:
    path: /home/vagrant/.profile
    state: touch
    mode: u+rw,g-rwx,o-rwx


- name: "Add new path into user .profile"
  become_user: vagrant
  lineinfile:
    dest: /home/vagrant/.profile
    state: present
    backrefs: no
    line: "export ANDROID_SDK_ROOT=/home/vagrant/android-sdk-linux:$ANDROID_SDK_ROOT\nexport ANDROID_HOME=/home/vagrant/android-sdk-linux:$ANDROID_HOME"

- name: add ANDROID_HOME
  become_user: vagrant
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: "{{ item }}"
  with_items:
    - 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64'
    - 'export ANDROID_HOME=/home/vagrant/android-sdk-linux'
    - 'export ANDROID_SDK_ROOT=$ANDROID_HOME'
    - 'export ANDROID_TOOLS=$ANDROID_HOME/tools/'
    - 'export ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform-tools/'
    - 'export PATH=$PATH:$ANDROID_TOOLS:$ANDROID_TOOLS/bin:$ANDROID_PLATFORM_TOOLS'   
   
- name: Sourse /etc/profile to find sdkmanager 
  become_user: vagrant
  become: no
  shell: source /etc/profile 
  args:
     executable: /bin/bash

- name: Sourse /home/vagrant/.bashrc  
  become_user: vagrant
  become: no
  shell: source /home/vagrant/.bashrc 
  args:
     executable: /bin/bash

- name: "Show list of available packages"
  become_user: vagrant
  become: no
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager --list
  register: list

- name: "SDK update"
  become_user: vagrant
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager --update 

- name: "Install platforms for android-26 "
  become_user: root
  become: yes
  expect:
    command: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager "platforms;android-26"
    responses:
      #\(yes/no\)\?: yes
      .Accept\? \(y/N\): y
    echo: yes 
    timeout: 300

#- name: "Install platfome for android-26"
#  become_user: vagrant
#  become: no
#  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager "platforms;android-26"
#  args:
#    executable: /bin/bash


- name: "Install build-tools for android"
  become_user: vagrant
  become: no
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager "build-tools;26.0.3" 
  args:
    executable: /bin/bash  

- name: Create a symbolic link for aapt
  file:
    src: /home/vagrant/android-sdk-linux/build-tools/26.0.3/aapt
    dest: /home/vagrant/android-sdk-linux/tools/bin/aapt
    owner: vagrant
    group: vagrant
    state: link

- name: "Install google;m2repository"
  become_user: vagrant
  become: no
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager "extras;google;m2repository" 
  args:
    executable: /bin/bash

- name: "Install android;m2repository"
  become_user: vagrant
  become: no
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager "extras;android;m2repository" 
  args:
    executable: /bin/bash    

- name: "Install tools google_apis;x86_64"
  become_user: vagrant
  become: no
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager "system-images;android-25;google_apis;x86_64"
  args:
    executable: /bin/bash

- name: Touch repositories.cfg
  become_user: vagrant
  file:
    path: /home/vagrant/.android/repositories.cfg
    state: touch
    mode: u+rw,g-wx,o-rwx

- name: "Install tools android-25 google_apis armeabi-v7a"
  become_user: vagrant
  become: no
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
  args:
    executable: /bin/bash

- name: "Ubuntu package updat"
  become_user: root
  become: yes
  shell: apt update

- name: "Create Android platform-tools directory"
  file:
    path: /home/vagrant/android-sdk-linux/platform-tools
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0777

- name: "Download and decompress Android-platform-tools from {{ linux_android_platformtools_url }}"
  unarchive: 
    copy: no
    src: "{{ linux_android_platformtools_url }}"
    dest:  /home/vagrant/android-sdk-linux/
    force: yes
    owner: vagrant
    group: vagrant
    mode: 0777

- name: "SDK update"                                                                                                                                                   
  become_user: vagrant                                                                                                                                                 
  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager --update


- name: "Make Vagrant owner for the directory"
  file:
    path: /home/vagrant/android-sdk-linux/
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0777
                                                                                                                                                                       
#- name: Creat emulator TestAvdArmV7a with android-25                                                                                                                  
#  become_user: vagrant                                                                                                                                                
#  shell: /home/vagrant/android-sdk-linux/tools/bin/avdmanager create avd -n TestAvdArmV7a -k "system-images;android-25;google_apis;armeabi-v7a" -d "Nexus 5X"         
#  args:                                                                                                                                                               
#     executable: /bin/bash

#- name: Install emulator                                                                                                                                              
#  become_user: vagrant                                                                                                                                                
#  shell: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager emulator                                                                                                
#  args:                                                                                                                                                               
#     executable: /bin/bash                                                                                                                                            
                                                                                                                                                                       
#- name: Start the emulator                                                                                                                                            
#  become_user: vagrant                                                                                                                                                
#  shell: /home/vagrant/android-sdk-linux/tools/emulator -avd TestAvdArmV7a                                                                                            
#  args:                                                                                                                                                               
#     executable: /bin/bash                                                                                                                                            
                                                                                                                                                                       
#add kvm acclerator cannot be used in a VMbox :(  https://linuxconfig.org/install-and-set-up-kvm-on-ubuntu-18-04-bionic-beaver-linux 