- name: Creates directory for appium
  become_user: root
  file:
    path:  /opt/gradle
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  become_user: vagrant
  become: yes
  unarchive:
    src: https://services.gradle.org/distributions/gradle-5.0-bin.zip
    dest: /opt/gradle
    remote_src: yes

- name: Create gradle.sh
  become_user: root
  file:
    path:  /etc/profile.d/gradle.sh
    state: touch
    owner: root
    group: root
    mode: 0777

- name: Update Profile with gradle.sh
  become_user: root
  copy: 
    content: "#!/bin/bash \n\n"
    dest: /etc/profile.d/gradle.sh

- name: Update environment variable with GRADLE_HOME
  become_user: root
  lineinfile:
    path: /etc/profile.d/gradle.sh
    line: "export GRADLE_HOME=/opt/gradle/gradle-5.0"

- name: Update environment variable with bin
  become_user: root
  lineinfile:
    path: /etc/profile.d/gradle.sh
    line: 'export PATH=${GRADLE_HOME}/bin:${PATH}'

- name: Make the script executable
  become_user: root
  file:
    path:  /etc/profile.d/gradle.sh
    state: file
    owner: root
    group: root
    mode: 0777

- name: Source /etc/profile.d/gradle.sh
  become_user: vagrant
  become: no
  shell: source /etc/profile.d/gradle.sh
  args:
     executable: /bin/bash

- name: Add gradle to Path in bashrc
  become_user: vagrant
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: "{{ item }}"
  with_items:
    - 'export GRADLE_HOME=/opt/gradle/gradle-5.0'
    - 'export PATH=${GRADLE_HOME}/bin:${PATH}'
    - 'export GORDON=gradletest'








