#Here to find adroid skd https://developer.android.com/studio/#downloads
#linux_android_commandline_url: "http://dl-ssl.google.com/android/repository/sdk-tools-linux-4333796.zip"
linux_android_commandline_url: "http://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
linux_android_platformtools_url: "http://dl.google.com/android/repository/platform-tools-latest-linux.zip"
android_tools_filter: "1,2,3,5,37"